/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.ReceitaController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Receita;
import model.dao.ReceitaDAO;

/**
 *
 * @author Jonas
 */
public class ViewJTable extends javax.swing.JFrame {

    
    
    Receita receita = new Receita();
    String id = "0";
    
    public ViewJTable() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTableReceita.getModel();
        jTableReceita.setRowSorter(new TableRowSorter(modelo));
        
        lerJTable();
        
    }
    public void lerJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTableReceita.getModel();
        modelo.setNumRows(0);
        ReceitaDAO dao = new ReceitaDAO();
        
        try {
            for(Receita receita : dao.listar("")){
                
                modelo.addRow(new Object[]{
                    receita.getId(),
                    receita.getNome(),
                    receita.getDescricao()
                    
                });
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewJTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void lerJTableBuscar(String buscar){
        DefaultTableModel modelo = (DefaultTableModel) jTableReceita.getModel();
        modelo.setNumRows(0);
        ReceitaController rc = new ReceitaController();
        
        try {
            for(Receita receita : rc.listar(buscar)){
                
                modelo.addRow(new Object[]{
                    receita.getId(),
                    receita.getNome(),
                    receita.getDescricao()
                    
                });
                
            }
        } catch (Exception ex) {
            Logger.getLogger(ViewJTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        botaoPesquisar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReceita = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("cadastro de receitas");
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel2.setText(" NOME DA RECEITA:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        botaoPesquisar.setText("PESQUISAR");
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        jButton2.setText("ADICIONAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("EXCLUIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CADASTRO DE RECEITAS");

        jTableReceita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RECEITA", "DESCRIÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableReceita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableReceitaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableReceita);
        if (jTableReceita.getColumnModel().getColumnCount() > 0) {
            jTableReceita.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton4.setText("VISUALIZAR RECEITA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("COMO FAZER:");

        jButton5.setText("EDITAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane3.setViewportView(txtDesc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoPesquisar)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed

        lerJTableBuscar(txtNome.getText());
        
        txtNome.setText("");
        txtDesc.setText("");
        
    }//GEN-LAST:event_botaoPesquisarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        boolean auxiliar;
        
        ReceitaController rc = new ReceitaController();
        
        try {
            auxiliar = rc.inserir(txtNome.getText(), txtDesc.getText());
            if (auxiliar == true){
                
                JOptionPane.showMessageDialog(null, "RECEITA CADASTRADA COM SUCESSO!");
            }else{
                JOptionPane.showMessageDialog(null, "PREENCHA A RECEITA PRIMEIRO.");
            } 
        } catch (Exception ex) {
            Logger.getLogger(ViewJTable.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        txtNome.setText("");
        txtDesc.setText("");
        
        lerJTable();
        
        
//        DefaultTableModel dtmReceita = (DefaultTableModel) jTableReceita.getModel();
//        Object[] dados = {txtNome.getText(),txtDesc.getText()};
//        dtmReceita.addRow(dados);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        ReceitaController rc = new ReceitaController();
        
        try {
            
            if(!id.equals("0")){
                rc.deletar(Integer.parseInt(id));
               JOptionPane.showMessageDialog(null, "DELETADO COM SUCESSO."); 
               this.id = "0";
            }else{
                JOptionPane.showMessageDialog(null, "OBJETO NÃO ENCONTRADO.");
            }
            
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, "ERRO INTERNO.");
        }
            
            txtNome.setText("");
            txtDesc.setText("");
            
            this.botaoPesquisarActionPerformed(evt);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTableReceitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableReceitaMouseClicked
        
        if(jTableReceita.getSelectedRow() != -1){
            
            txtNome.setText(jTableReceita.getValueAt(jTableReceita.getSelectedRow(), 1).toString());
            txtDesc.setText(jTableReceita.getValueAt(jTableReceita.getSelectedRow(), 2).toString());
            id = jTableReceita.getValueAt(jTableReceita.getSelectedRow(), 0).toString();
            
            receita.setId(Integer.parseInt(id));
            receita.setDescricao(jTableReceita.getValueAt(jTableReceita.getSelectedRow(), 2).toString());
            receita.setNome(jTableReceita.getValueAt(jTableReceita.getSelectedRow(), 1).toString());
        }
        
        System.out.println(receita.getId());
        System.out.println(receita.getNome());
        System.out.println(receita.getDescricao());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableReceitaMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String id = Integer.toString(receita.getId());
        System.out.println(receita.getId());
        System.out.println(receita.getNome());
        System.out.println(receita.getDescricao());
        TelaVisualizar telavisualizar = new TelaVisualizar(id,receita.getNome(), receita.getDescricao());
        this.setVisible(false);
        telavisualizar.setVisible(true );
            
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    boolean auxiliar;
        int cod = Integer.parseInt(id);
        ReceitaController rc = new ReceitaController();
        
        try {
            auxiliar = rc.alterar(cod, txtNome.getText(), txtDesc.getText());
            if (auxiliar == true){
                
                JOptionPane.showMessageDialog(null, "RECEITA ALTERADA COM SUCESSO!");
            }else{
                JOptionPane.showMessageDialog(null, "PREENCHA OS CAMPOS PRIMEIRO.");
            } 
        } catch (Exception ex) {
            Logger.getLogger(ViewJTable.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        txtNome.setText("");
        txtDesc.setText("");
        
        this.botaoPesquisarActionPerformed(evt);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewJTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableReceita;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
